#! /bin/sh

# Preparation
# make sure you have the following command line programs:
# jq
# uuidgen


# Steps to run the tests
# setup and run the firestore emulator in a different shell
# execute ./tests
# or, alternativelt, run specific tests with ./tests -- nameoffirsttest nameofsecondtest


oneTimeSetUp() {
    export FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST:=localhost:8080}
    echo "Running tests againt ${FIRESTORE_EMULATOR_HOST}. (make sure firestore emulator is running)."
    # rebuild the executable to make sure tests match the latest source code
    go build -o ../fuego  ..
    sleep 1
}

setUp() {
    TEST_COLLECTION=tests-`uuidgen`
    TEST_COLLECTION_2=tests-`uuidgen`
    echo "Testing with collection ${TEST_COLLECTION}"
}

oneTimeTearDown() {
    echo "DONE"
}

testAddSetReadDeleteDocument() {
    # Adding...
    expectedValue="string1"
    id=$(../fuego add ${TEST_COLLECTION} "{\"level1\": \"${expectedValue}\"}") || fail "Failed to add document"
    result=$(../fuego get ${TEST_COLLECTION} ${id} | jq ".Data.level1")
    assertEquals "Failed to read added value" "\"${expectedValue}\"" "${result}"

    # Setting...
    expectedValue="string2"
    ../fuego set ${TEST_COLLECTION} ${id} "{\"level1\": \"${expectedValue}\"}" || fail "Failed to set document"
    result=$(../fuego get ${TEST_COLLECTION} ${id} | jq ".Data.level1")
    assertEquals "Failed to read set value" "\"${expectedValue}\"" "${result}"

		# Also test reading using document-path
    result=$(../fuego get ${TEST_COLLECTION}/${id} | jq ".Data.level1")
    assertEquals "Failed to read set value" "\"${expectedValue}\"" "${result}"

		# And deleting...
		../fuego delete ${TEST_COLLECTION} ${id}
		assertFalse "Should not have read deleted value" "../fuego get ${TEST_COLLECTION} ${id}"
}

testGetAllDocuments() {
    # Adding...
    expectedValue1="string1"
    expectedValue2="string2"
    id1=$(../fuego add ${TEST_COLLECTION} "{\"level1\": \"${expectedValue1}\"}") || fail "Failed to add document"
    id2=$(../fuego add ${TEST_COLLECTION} "{\"level1\": \"${expectedValue2}\"}") || fail "Failed to add document"
    result=$(../fuego getall ${TEST_COLLECTION} ${id1} ${id2} | jq -r '.[].Data.level1'| tr '\n' ' ')
    assertEquals "Failed to read all added value" "${expectedValue1} ${expectedValue2} " "${result}"
}

testDeleteAllDocuments() {
    # Adding...
    expectedValue1="string1"
    expectedValue2="string2"
    id1=$(../fuego add ${TEST_COLLECTION} "{\"level1\": \"${expectedValue1}\"}") || fail "Failed to add document"
    id2=$(../fuego add ${TEST_COLLECTION} "{\"level1\": \"${expectedValue2}\"}") || fail "Failed to add document"
    ../fuego deleteall ${TEST_COLLECTION} ${id1} ${id2} > /dev/null
    result=$(../fuego query ${TEST_COLLECTION})
    assertEquals "Failed to delete documents." "" "${result}"
}

testUpdatingDocument(){
    # add a new document
    id=$(../fuego add ${TEST_COLLECTION} "{\"level1\": \"value\"}") || fail "Failed to add document"

    # add a new field using document path
    ../fuego set --merge ${TEST_COLLECTION}/${id} "{\"version\": 2}" || fail "Failed to add document"
    result=$(../fuego get ${TEST_COLLECTION} ${id} | jq .Data)
    expectedValue=$(echo {\"level1\": \"value\", \"version\": 2} | jq .)
    assertEquals "Failed to update new fields" "${expectedValue}" "${result}"

    # overwrite existing field
    ../fuego set --merge ${TEST_COLLECTION} ${id} "{\"version\": 15}" || fail "Failed to add document"
    result=$(../fuego get ${TEST_COLLECTION} ${id} | jq .Data)
    expectedValue=$(echo {\"level1\": \"value\", \"version\": 15} | jq .)
    assertEquals "Failed to update existing fields" "${expectedValue}" "${result}"
}

testUpdatingDeepDocument(){
    # add a new document
    id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\"}") || fail "Failed to add document"

    # add a new field
    ../fuego set --merge ${TEST_COLLECTION} ${id} "{\"level1\": {\"level2\": {\"level3\": {\"level4\": \"value\"}}}}" || fail "Failed to add document"
    result=$(../fuego get ${TEST_COLLECTION} ${id} | jq .Data)
    expectedValue=$(echo {\"base\": \"value\", \"level1\": {\"level2\": {\"level3\": {\"level4\": \"value\"}}}} | jq .)
    assertEquals "Failed to update deeply nested field fields" "${expectedValue}" "${result}"
}

testQueryKeys(){
    # Query integer value on first level key
    id=$(../fuego add ${TEST_COLLECTION} "{\" \": 1, \"level1\": 1, \"level2root\": {\"number\": 1}}") || fail "Failed to add document"
    result=$(../fuego query ${TEST_COLLECTION} "level1 == 1" | jq ".[0].ID")
    assertEquals "Failed to query integer on first level key" "\"${id}\"" "$result"

    # Query integer value on second level key
    result=$(../fuego query ${TEST_COLLECTION} "level2root.number == 1" | jq ".[0].ID")
    assertEquals "Failed to query integer on second level key" "\"${id}\"" "$result"

    # Query integer on empty key using string as key
    result=$(../fuego query ${TEST_COLLECTION} "\" \" == 1" | jq ".[0].ID")
    assertEquals "Failed to query value on empty key" "\"${id}\"" "$result"

	# Combine quoting and non quoting parts of a key
    result=$(../fuego query ${TEST_COLLECTION} "\"level2root\".number == 1" | jq ".[0].ID")
    assertEquals "Failed to query value combining quoting and non quoting parts of a key" "\"${id}\"" "$result"
}

testQueryWithSelect(){
    ../fuego add ${TEST_COLLECTION} "{\"p1\": 1, \"p2\": {\"number\": 1, \"string\":\"blah\"}}"
    result=$(../fuego query --select p1 --select '"p2".number' ${TEST_COLLECTION} "p1 == 1" | jq -c ".[0].Data")
    assertEquals "Failed to select properties" "{\"p1\":1,\"p2\":{\"number\":1}}" "${result}"
}

testGroupQuery() {
    ../fuego set ${TEST_COLLECTION}/doc1/${TEST_COLLECTION_2}/doc1_1 '{}'
    ../fuego set ${TEST_COLLECTION}/doc1/${TEST_COLLECTION_2}/doc1_2 '{}'
    ../fuego set ${TEST_COLLECTION}/doc2/${TEST_COLLECTION_2}/doc2_1 '{}'
    ../fuego set ${TEST_COLLECTION}/doc2/${TEST_COLLECTION_2}/doc2_2 '{}'
    result=$(../fuego query -g ${TEST_COLLECTION_2} | jq '. | length')
    assertEquals "Failed to query group collection" "4" "${result}"
}

testQueryDifferentValueTypes(){
    id=$(../fuego add ${TEST_COLLECTION} "{\"number\": 1, \"timestamp\": {\"\$date\": \"2019-02-26T02:39:44.458Z\"}, \"string\": \"string1\", \"bool\": true, \"array\": [1, 2, 3]}") || fail "Failed to add document"

    id2=$(../fuego add ${TEST_COLLECTION} "{\"number\": 100, \"timestamp\": {\"\$date\": \"2022-06-23T02:39:44.458Z\"}, \"string\": \"string2\", \"bool\": false, \"array\": [4, 5, 6]}") || fail "Failed to add document"

    # equality
    result=$(../fuego query ${TEST_COLLECTION} "number == 1" | jq ".[0].ID")
    assertEquals "Failed to query integer on value" "\"${id}\"" "$result"

    # inequality
    result=$(../fuego query ${TEST_COLLECTION} "number != 1" | jq ".[0].ID")
    assertEquals "Failed to query integer on not value" "\"${id2}\"" "$result"

    # Query timestamp
    result=$(../fuego query ${TEST_COLLECTION} "timestamp == 2019-02-26T02:39:44.458Z" | jq ".[0].ID")
    assertEquals "Failed to query timestamp" "\"${id}\"" "$result"

    # query string double quote
    result=$(../fuego query ${TEST_COLLECTION} "string == \"string1\"" | jq ".[0].ID")
    assertEquals "Failed to query timestamp" "\"${id}\"" "$result"

    # query string dsingle quote
    result=$(../fuego query ${TEST_COLLECTION} "string == 'string1'" | jq ".[0].ID")
    assertEquals "Failed to query timestamp" "\"${id}\"" "$result"

    # query bool
    result=$(../fuego query ${TEST_COLLECTION} "bool == true" | jq ".[0].ID")
    assertEquals "Failed to query timestamp" "\"${id}\"" "$result"

    # in
    result=$(../fuego query ${TEST_COLLECTION} "number <in> [1 2 3]" | jq ".[0].ID")
    assertEquals "Failed to query integer in values" "\"${id}\"" "$result"

    # not-in
    result=$(../fuego query ${TEST_COLLECTION} "string <not-in> [\"string1\"]" | jq ".[0].ID")
    assertEquals "Failed to query string not-in values" "\"${id2}\"" "$result"

    # array-contains
    result=$(../fuego query ${TEST_COLLECTION} "array <array-contains> 1" | jq ".[0].ID")
    assertEquals "Failed to query integer on value" "\"${id}\"" "$result"

    # array-contains-any
    result=$(../fuego query ${TEST_COLLECTION} "array <array-contains-any> [1]" | jq ".[0].ID")
    assertEquals "Failed to query integer on value" "\"${id}\"" "$result"
}

testExtendedJson() {
    # insert several types.
    id=$(../fuego add ${TEST_COLLECTION} '{"intval": {"$numberInt": 1}, "doubleval": {"$numberDouble": 1}, "innerIntval": {"intval": {"$numberInt": 1}}, "arrayIntval": [{"$numberInt": 1}], "dateval": {"$date": "2019-02-26T02:39:44.458Z"}, "geopointval": {"$geopoint": {"$latitude": 1, "$longitude": 2}}, "binaryval": {"$binary": "aGVsbG93b3JsZA=="}, "stringval": {"$string": "helloworld"}}')
    result=$(../fuego get -ej ${TEST_COLLECTION} $id)

    intval=$(echo $result | jq '.Data.intval."$numberInt"')
    assertEquals "Failed to fetch numberInt" "1" "${intval}"

    doubleval=$(echo $result | jq '.Data.doubleval."$numberDouble"')
    assertEquals "Failed to fetch numberDouble" "1" "${doubleval}"

    innerIntval=$(echo $result | jq '.Data.innerIntval.intval."$numberInt"')
    assertEquals "Failed to fetch a nested numberInt " "1" "${innerIntval}"

    arrayIntval=$(echo $result | jq '.Data.arrayIntval[0]."$numberInt"')
    assertEquals "Failed to fetch a numberInt within an array" "1" "${arrayIntval}"

    latitude=$(echo $result | jq '.Data.geopointval."$geopoint"."$latitude"')
    longitude=$(echo $result | jq '.Data.geopointval."$geopoint"."$longitude"')

    assertEquals "Failed to fetch a latitude " "1" "${latitude}"
    assertEquals "Failed to fetch a longitude " "2" "${longitude}"

    dateval=$(echo $result | jq '.Data.dateval."$date"')
    assertEquals "Failed to fetch a date" "\"2019-02-26T02:39:44.458Z\"" "$dateval"

    stringval=$(echo $result | jq '.Data.stringval."$string"')
    assertEquals "Failed to fetch a date" "\"helloworld\"" "$stringval"

    binaryval=$(echo $result | jq '.Data.binaryval."$binary"')
    assertEquals "Failed to fetch a date" "\"aGVsbG93b3JsZA==\"" "$binaryval"
}


testQueryInequality(){
    # query bigger than
    for i in $(seq 1 3); do
        ../fuego add ${TEST_COLLECTION} "{\"level1\": {\"level2\": $i}}"
    done

    result=$(../fuego query ${TEST_COLLECTION} "level1.level2 > 2" | jq "length")
    assertEquals "Failed to query >" "1" "$result"

    # less than or equal
    result=$(../fuego query ${TEST_COLLECTION} "level1.level2 <= 2" | jq "length")
    assertEquals "Failed to query <=" "2" "$result"
}

testCompoundQuery(){
    ../fuego add ${TEST_COLLECTION} "{\"key1\": \"key1\", \"key2\": 2}" || fail "Failed to add document"
    ../fuego add ${TEST_COLLECTION} "{\"key1\": \"whatever\", \"key2\": 2}" || fail "Failed to add document"

    # query first on a single field
    result=$(../fuego query ${TEST_COLLECTION} "key2 == 2" | jq "length")
    assertEquals "Failed to query on a single key" "2" "$result"


    # query first on two fields
    result=$(../fuego query ${TEST_COLLECTION} "key2 == 2" "key1 == \"key1\"" | jq "length")
    assertEquals "Failed to query on two keys" "1" "$result"

    # query on two fields, that fail
    result=$(../fuego query ${TEST_COLLECTION} "key2 == 1" "key1 == \"key1\"")
    assertEquals "Failed to query on two keys" "" "$result"

}


testOrderAndPagination(){
    r1=$(../fuego add ${TEST_COLLECTION} "{\"level1\": {\"level2\": 1}}")
    r2=$(../fuego add ${TEST_COLLECTION} "{\"level1\": {\"level2\": 2}}")
    r3=$(../fuego add ${TEST_COLLECTION} "{\"level1\": {\"level2\": 3}}")

    # limit 1 result
    result=$(../fuego query --limit 1 ${TEST_COLLECTION}  | jq "length")
    assertEquals "Failed to set a limit" "1" "$result"

    # order ASC
    result=$(../fuego query --limit 1 --orderby 'level1.level2' --orderdir ASC ${TEST_COLLECTION}  | jq ".[0].Data.level1.level2")
    assertEquals "Failed to order ASC" "1" "$result"

    # order DESC
    result=$(../fuego query --limit 1 --orderby 'level1.level2' --orderdir DESC ${TEST_COLLECTION}  | jq ".[0].Data.level1.level2")
    assertEquals "Failed to order DESC" "3" "$result"

    # Start at
    result=$(../fuego query --limit 1 --orderby 'level1.level2' --orderdir DESC --startat ${r2} ${TEST_COLLECTION}  | jq ".[0].ID")
    assertEquals "startat failed" "$result" "\"$r2\""

		# Start at using document path
		result=$(../fuego query --limit 1 --orderby 'level1.level2' --orderdir DESC --startat ${TEST_COLLECTION}/${r2} ${TEST_COLLECTION}  | jq ".[0].ID")
    assertEquals "startat failed" "$result" "\"$r2\""

    # Start after
		result=$(../fuego query --limit 1 --orderby 'level1.level2' --orderdir DESC --startafter ${r2} ${TEST_COLLECTION}  | jq ".[0].ID")
    assertEquals "startat failed" "$result" "\"$r1\""

		# Start after using document path
    result=$(../fuego query --limit 1 --orderby 'level1.level2' --orderdir DESC --startafter ${TEST_COLLECTION}/${r2} ${TEST_COLLECTION}  | jq ".[0].ID")
    assertEquals "startat failed" "$result" "\"$r1\""

    # End at
    result=$(../fuego query --orderby 'level1.level2' --orderdir DESC --endat ${r2} ${TEST_COLLECTION}  | jq "length")
    assertEquals "endat failed" "2" "$result"

		# End at using document path
    result=$(../fuego query --orderby 'level1.level2' --orderdir DESC --endat ${TEST_COLLECTION}/${r2} ${TEST_COLLECTION}  | jq "length")
    assertEquals "endat failed" "2" "$result"

    # End before
    result=$(../fuego query --orderby 'level1.level2' --orderdir DESC --endbefore ${r2} ${TEST_COLLECTION}  | jq "length")
    assertEquals "endbefore failed" "1" "$result"

		# End before using document path
    result=$(../fuego query --orderby 'level1.level2' --orderdir DESC --endbefore ${TEST_COLLECTION}/${r2} ${TEST_COLLECTION}  | jq "length")
    assertEquals "endbefore failed" "1" "$result"
}

testParsingFieldPaths(){
    r1=$(../fuego add ${TEST_COLLECTION} "{\"le.vel1\": {\" level2 \": 1, \"a\": 1}}")
    r2=$(../fuego add ${TEST_COLLECTION} "{\"le.vel1\": {\" level2 \": 2, \"a\": 2}}")
    r3=$(../fuego add ${TEST_COLLECTION} "{\"le.vel1\": {\" level2 \": 3, \"a\": 3}}")

    # order ASC
    result=$(../fuego query --select "\"le.vel1\".' level2 '" --limit 1 --orderby "\"le.vel1\".' level2 '" --orderdir ASC ${TEST_COLLECTION}  | jq -c ".[0].Data" )
    assertEquals "Failed to query parsing difficult field paths" "{\"le.vel1\":{\" level2 \":1}}" "$result"

}

testCopyDocumentAndCollection(){
    # add a new document
    id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\"}") || fail "Failed to add document"
    subDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1" "{\"base\": \"sub value1\"}") || fail "Failed to add document"
    subDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2" "{\"base\": \"sub value2\"}") || fail "Failed to add document"
    echo ${id} ${subDocId1} ${subDocId2}
    targetDocumentPath=${TEST_COLLECTION}/$(uuidgen)
    targetCollectionPath=$(uuidgen)

    ../fuego copy "${TEST_COLLECTION}/${id}" ${targetDocumentPath} --overwrite
    ../fuego copy "${TEST_COLLECTION}" ${targetCollectionPath} --overwrite

    # query copied document
    result=$(../fuego get ${targetDocumentPath} | jq .Data)
    expectedValue=$(echo {\"base\": \"value\"} | jq .)
    assertEquals "Failed to copy document" "${expectedValue}" "${result}"

    result=$(../fuego get "${targetDocumentPath}/subCollection1/${subDocId1}" | jq .Data)
    expectedValue=$(echo {\"base\": \"sub value1\"} | jq .)
    assertEquals "Failed to copy document" "${expectedValue}" "${result}"

    result=$(../fuego get "${targetDocumentPath}/subCollection2/${subDocId2}" | jq .Data)
    expectedValue=$(echo {\"base\": \"sub value2\"} | jq .)
    assertEquals "Failed to copy document" "${expectedValue}" "${result}"

    # query copied collection
    result=$(../fuego get "${targetCollectionPath}/${id}" | jq .Data)
    expectedValue=$(echo {\"base\": \"value\"} | jq .)
    assertEquals "Failed to copy document" "${expectedValue}" "${result}"

    result=$(../fuego get "${targetCollectionPath}/${id}/subCollection1/${subDocId1}" | jq .Data)
    expectedValue=$(echo {\"base\": \"sub value1\"} | jq .)
    assertEquals "Failed to copy document" "${expectedValue}" "${result}"

    result=$(../fuego get "${targetCollectionPath}/${id}/subCollection2/${subDocId2}" | jq .Data)
    expectedValue=$(echo {\"base\": \"sub value2\"} | jq .)
    assertEquals "Failed to copy document" "${expectedValue}" "${result}"
}

testDeleteRecursive(){
    # adding new documents with nested sub-collections
    id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\"}") || fail "Failed to add document"
    subDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1" "{\"base\": \"sub value1\"}") || fail "Failed to add document"
    subSubDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1" "{\"base\": \"subsub value1\"}")|| fail "Failed to add document"

    subDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2" "{\"base\": \"sub value2\"}") || fail "Failed to add document"
    subSubDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection2/${subDocId2}/subSubCollection2" "{\"base\": \"subsub value2\"}")|| fail "Failed to add document"
    echo ${id} ${subDocId1} ${subSubDocId1} ${subDocId2} ${subSubDocId2}

    # delete one collection without recursive flag. To test deletion of missing documents.
    ../fuego delete "${TEST_COLLECTION}/${id}/subCollection1" ${subDocId1}
    assertFalse "Should not have read deleted value" "../fuego get ${TEST_COLLECTION}/${id}/subCollection1 ${subDocId1}"

    # check that sub-collection of deleted collection still exists
    expectedValue=$(echo "{\"base\": \"subsub value1\"}" | jq .)
    result=$(../fuego get "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1/${subSubDocId1}"  | jq .Data)
    assertEquals "Should be able to read SubCollection" "${result}" "${expectedValue}"

    # call delete again, but with recursive flag.
    ../fuego delete -r "${TEST_COLLECTION}" ${id}

    # check that all documents are deleted, also the missing documents.
    assertFalse "Should not have read deleted value2" "../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subSubCollection1 ${subSubDocId1}"
    assertFalse "Should not have read deleted value3" "../fuego get ${TEST_COLLECTION}/${id}/subCollection2 ${subDocId2}"
    assertFalse "Should not have read deleted value2" "../fuego get ${TEST_COLLECTION}/${id}/subCollection2/${subDocId2}/subSubCollection2 ${subSubDocId2}"
}

testFieldDelete(){
    # adding new documents with sub-collections and two fields
    id=$(../fuego add ${TEST_COLLECTION} "{\"base\": \"value\", \"base2\": \"value2\"}") || fail "Failed to add document"
    subDocId1=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1" "{\"subbase\": \"sub value1\"}") || fail "Failed to add document"
    subDocId2=$(../fuego add "${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}/subCollection2" "{\"sub2base\": \"sub2 value1\"}") || fail "Failed to add document"
    echo ${id} ${subDocId1} ${subDocId2}

    # check preconditions for first level
    result=$(../fuego get ${TEST_COLLECTION}/${id} | jq -c .Data)
    expectedValue='{"base":"value","base2":"value2"}'
    assertEquals "Preconditions Failed" "${result}" "${expectedValue}"

    # delete field from first level
    ../fuego delete -f "base2" ${TEST_COLLECTION}/${id}
    result=$(../fuego get ${TEST_COLLECTION}/${id} | jq -c .Data)
    expectedValue='{"base":"value"}'
    assertEquals "Failed to delete from First level" "${result}" "${expectedValue}"

    # check preconditions for second level
    result=$(../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1} | jq -c .Data)
    expectedValue='{"subbase":"sub value1"}'
    assertEquals "Preconditions Failed" "${result}" "${expectedValue}"
    
    # delete field from second level
    ../fuego delete -f "subbase" ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1}
    result=$(../fuego get ${TEST_COLLECTION}/${id}/subCollection1/${subDocId1} | jq -c .Data)
    expectedValue='{}'
    assertEquals "Failed to delete from First level" "${result}" "${expectedValue}"
}

# Load shUnit2.
. ./shunit2
